# Generated by Django 2.2.16 on 2020-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgateway_app', '0002_auto_20200916_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('in-progress', 'In-Progress')], default='success', max_length=255),
        ),
    ]
